### ISSUE TITLE
Exception on bad request when patching publisher bid

### ISSUE THREAD

**Issue by pawel-sekara** [taboola/backstage-api-java-client#27]
```
java.util.UnknownFormatConversionException: Conversion = ']'
	at java.base/java.util.Formatter.checkText(Formatter.java:2732)
	at java.base/java.util.Formatter.parse(Formatter.java:2718)
	at java.base/java.util.Formatter.format(Formatter.java:2655)
	at java.base/java.util.Formatter.format(Formatter.java:2609)
	at java.base/java.lang.String.format(String.java:2897)
	at com.taboola.backstage.exceptions.BackstageAPIException.<init>(BackstageAPIException.java:20)
	at com.taboola.backstage.exceptions.BackstageAPIRequestException.<init>(BackstageAPIRequestException.java:18)
	at com.taboola.backstage.internal.SynchronousCallAdapterFactory$1.adapt(SynchronousCallAdapterFactory.java:70)
	at retrofit2.HttpServiceMethod$CallAdapted.adapt(HttpServiceMethod.java:148)
	at retrofit2.HttpServiceMethod.invoke(HttpServiceMethod.java:132)
	at retrofit2.Retrofit$1.invoke(Retrofit.java:149)
	at com.sun.proxy.$Proxy152.patchCampaign(Unknown Source)
	at com.taboola.backstage.services.CampaignsServiceImpl.patch(CampaignsServiceImpl.java:66)
```

It happens when such response is sent: 
{"http_status":400,"message":"Cpc boost value must be between -99% and 100%","offending_field":""}

Problem is with String.format being called twice, when error message gets replaced by message, it produces %], which is incorrect for 2nd String.format call

**Comment by vladimanaev** [comment]
@pawel-sekara thanks for raising this, we will patch it in the upcoming version.

**Comment by vladimanaev** [comment]
Part of 1.0.15
